source 'https://rubygems.org'

# Upgraded dependencies - resolving known vulnerabilities
gem 'rails', '7.1.5'
gem 'nokogiri', '1.18.1'
gem 'rack', '2.2.10'
gem 'puma', '5.6.9'
gem 'actionpack', '7.1.5'
gem 'activerecord', '7.1.5'
gem 'actionview', '7.1.5'
gem 'activesupport', '7.1.5'
gem 'loofah', '2.23.1'
gem 'rails-html-sanitizer', '1.6.1'
