source 'https://rubygems.org'

# Test dependencies with known vulnerabilities
gem 'rails', '6.1.4'
gem 'nokogiri', '1.12.5'
gem 'rack', '2.2.3'
gem 'puma', '5.5.2'
gem 'actionpack', '6.1.4'
gem 'activerecord', '6.1.4'
gem 'actionview', '6.1.4'
gem 'activesupport', '6.1.4'
gem 'loofah', '2.12.0'
gem 'rails-html-sanitizer', '1.4.2'
